### ISSUE TITLE
[Help] Can't build with MUSL toolchain

### ISSUE THREAD

**Issue by ggomagundan** [zmwangx/rust-ffmpeg#10]
I try to build with Musl toolchain and get follow error message

```
$ cargo build --release --target x86_64-unknown-linux-musl
   Compiling openssl v0.10.26
   Compiling bytes v0.4.12
   Compiling serde_json v1.0.44
   Compiling futures-util v0.3.5
   Compiling chrono v0.4.10
   Compiling tokio-util v0.3.1
   Compiling time v0.2.16
   Compiling ffmpeg-sys-next v4.2.0
error: failed to run custom build command for `ffmpeg-sys-next v4.2.0`

Caused by:
  process didn't exit successfully: `~/rust_project/target/release/build/ffmpeg-sys-next-b82962bdaa9b57bd/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CrossCompilation', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/ffmpeg-sys-next-4.2.0/build.rs:547:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
```

Could you give me some advices?

**Comment by zmwangx** [comment]
Panicked here: https://github.com/zmwangx/rust-ffmpeg-sys/blob/aaccc155d1dc0d21751a80d676fcf5d82075cdc7/build.rs#L547 when trying to find libavutil with pkg-config. Presumably libavutil isn’t installed. You need to make sure libavutil as well as other libav* corresponding to the enabled features are installed.

Guess I should improve error reporting instead of just panicking.

**Comment by ggomagundan** [comment]
Thanks to you advice.

But I already installed ffmpeg utils

```
$ ffmpeg -version

ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
built with Apple clang version 11.0.3 (clang-1103.0.32.59)
configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.3_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags=-fno-stack-check --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
``` 

And If I remove `--target x86_64-unknown-linux-musl` options, It can be build.

But I wanna build with `linux-musl`

**Comment by zmwangx** [comment]
Oh, didn’t notice you’re cross compiling.

At a minimum you need to set `PKG_CONFIG_ALLOW_CROSS=1`.

https://docs.rs/pkg-config/0.3.17/pkg_config/enum.Error.html#variant.CrossCompilation

I haven’t tried to cross compile myself so not sure if you’ll run into other problems, don’t have time to check. Let me know how it goes.

**Comment by ggomagundan** [comment]
I tried it.

And it also not passed :(

```
$ PKG_CONFIG_ALLOW_CROSS=true cargo build --target=x86_64-unknown-linux-musl

   Compiling cfg-if v0.1.10
   Compiling lazy_static v1.4.0
.......
   Compiling failure v0.1.8
   Compiling ffmpeg-sys-next v4.2.0
error: failed to run custom build command for `ffmpeg-sys-next v4.2.0`

Caused by:
  process didn't exit successfully: `/projects/rust/target/debug/build/ffmpeg-sys-next-aac5d45e989d421c/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/usr/local/Cellar/ffmpeg/4.2.3_1/lib
cargo:rustc-link-lib=avutil
cargo:rustc-link-search=native=/usr/local/Cellar/ffmpeg/4.2.3_1/lib
cargo:rustc-link-lib=avformat
cargo:rustc-link-search=native=/usr/local/Cellar/ffmpeg/4.2.3_1/lib
cargo:rustc-link-lib=avfilter
cargo:rustc-link-search=native=/usr/local/Cellar/ffmpeg/4.2.3_1/lib
cargo:rustc-link-lib=avdevice
cargo:rustc-link-search=native=/usr/local/Cellar/ffmpeg/4.2.3_1/lib
cargo:rustc-link-lib=swscale
cargo:rustc-link-search=native=/usr/local/Cellar/ffmpeg/4.2.3_1/lib
cargo:rustc-link-lib=swresample
cargo:rustc-link-search=native=/usr/local/Cellar/ffmpeg/4.2.3_1/lib
cargo:rustc-link-lib=avcodec
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-musl")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-unknown-linux-musl = None
CC_x86_64_unknown_linux_musl = None
TARGET_CC = None
CC = None
CROSS_COMPILE = None
CFLAGS_x86_64-unknown-linux-musl = None
CFLAGS_x86_64_unknown_linux_musl = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,mmx,sse,sse2")
stdout=

--- stderr
check.c:311:0: warning: "FF_API_XVMC_is_defined" redefined
             #define FF_API_XVMC_is_defined 1
 
check.c:84:0: note: this is the location of the previous definition
             #define FF_API_XVMC_is_defined 0
 
thread 'main' panicked at 'Variable not found in output', /PJT/.cargo/registry/src/github.com-1ecc6299db9ec823/ffmpeg-sys-next-4.2.0/build.rs:427:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
```


anyway I'll try to find other way.

**Comment by zmwangx** [comment]
Closing due to lack of activity.
