### ISSUE TITLE
ffmpeg v5.1.1 seems broken

### ISSUE THREAD

**Issue by SomaticIT** [zmwangx/rust-ffmpeg#118]
*Please include as much info as possible to save me (solo maintainer helping for free) some time. A [minimal, complete, and reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) is a must. Link to a gist if you don't feel like posting all the code inline. At the same time, please leave out unnecessary code so I don't need to wade through a hundred lines to get to the problematic part. Tell me your OS, FFmpeg version, etc. if there's even a slim chance of relevancy.*

Hello,

Thank you for your work on this project. It allows a lot of awesome implementations of ffmpeg.

I'm trying to make this work with `ffmpeg` v5.1.1 (with `ffmpeg-next` v5.1.1).
However I'm facing many issues with the `transcode-x264.rs` example.

Here is an output of running the example:
```
x264 options: {"preset": "medium"}
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/path/to/video.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2021-08-25T09:45:49.000000Z
  Duration: 00:00:16.04, start: 0.000000, bitrate: 2549 kb/s
  Stream #0:0[0x1](eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 2170 kb/s, 29.97 fps, 29.97 tbr, 30k tbn (default)
    Metadata:
      creation_time   : 2021-08-25T09:45:49.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2021-08-25T09:45:49.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
      vendor_id       : [0][0][0][0]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', def/main.rs:62:52
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:775:21
   4: def::Transcoder::new
             at ./def/main.rs:62:31
   5: def::main
             at ./def/main.rs:210:17
   6: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

As you can see, the `decoder.frame_rate()` is `None` but it's not the case when using v4.
If I try to enforce `frame_rate` and `time_base` with static values, I have this error:
```
x264 options: {"preset": "medium"}
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/path/to/video.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2021-08-25T09:45:49.000000Z
  Duration: 00:00:16.04, start: 0.000000, bitrate: 2549 kb/s
  Stream #0:0[0x1](eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 2170 kb/s, 29.97 fps, 29.97 tbr, 30k tbn (default)
    Metadata:
      creation_time   : 2021-08-25T09:45:49.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2021-08-25T09:45:49.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
      vendor_id       : [0][0][0][0]
[NULL @ 0x5630fb191800] No codec provided to avcodec_open2()
thread 'main' panicked at 'error opening libx264 encoder with supplied settings: ffmpeg::Error(22: Invalid argument)', def/main.rs:69:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
   3: core::result::Result<T,E>::expect
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1064:23
   4: def::Transcoder::new
             at ./def/main.rs:67:9
   5: def::main
             at ./def/main.rs:210:17
   6: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Any idea?

**Comment by marcusstenbeck** [comment]
I see this same problem using `ffmpeg` 5.1.2 and `ffmpeg-next` v5.1.1

**Comment by gil0mendes** [comment]
I did a quick test and seems like if we pass a codec to `avcodec_alloc_context3` instead of a null pointer, it works. 🤔 

```rust
impl Context {
    pub fn new() -> Self {
        unsafe {
            let codec = super::encoder::find_by_name("libx264").unwrap();
            Context {
                ptr: avcodec_alloc_context3(codec.as_ptr()),
                owner: None,
            }
        }
    }
```

The function docs can be found [here](https://ffmpeg.org/doxygen/4.0/group__lavc__core.html#gae80afec6f26df6607eaacf39b561c315).

This was the code that I used to test:
```rust
let encoder = AvContext::from_parameters(writer_stream.parameters())?
            .encoder()
            .video()?;
```

**Comment by SnyderTheOne** [comment]
Even with the change of @gil0mendes, I'm still unable to instantiate a 'open' a libx264 encoder. Did anyone manage to get the x264 transcoding example working on ffmpeg 5.0.0 or higher?

**Comment by eliasericsson** [comment]
Finding myself in the same seat as @SnyderTheOne, unable to run the x264 transcoding example with ffmpeg 5.1.1

**Comment by SverreEplov** [comment]
What use statement did you use to get avcodec_open2 in scope ? 

br,
 /Sverre Eplov

**Comment by 1392492818** [comment]
use ffmpeg_sys_next::avcodec_open2;





F.M
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zmwangx/rust-ffmpeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 凌晨4:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zmwangx/rust-ffmpeg] ffmpeg v5.1.1 seems broken (Issue #118)





 
What use statement did you use to get avcodec_open2 in scope ?
 
br,
 /Sverre Eplov

**Comment by 1392492818** [comment]
use ffmpeg_sys_next::avcodec_open2;







F.M
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zmwangx/rust-ffmpeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 凌晨4:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zmwangx/rust-ffmpeg] ffmpeg v5.1.1 seems broken (Issue #118)





 
What use statement did you use to get avcodec_open2 in scope ?
 
br,
 /Sverre Eplov

**Comment by Sculas** [comment]
Encountering this issue as well on FFmpeg 5.1.2 (ffmpeg-next 6.0.0)

**Comment by fuzing** [comment]
Looks like at there were several breaking changes to the ffmpeg API that have not made it to the APIs for this project, leading to this (and other) examples not working.

For example:

this line:
```
       let mut ost = octx.add_stream(encoder::find(codec::Id::H264))?;
```

results in a call to:
```
      AVStream * avformat_new_stream (AVFormatContext *s, const AVCodec *c)
```

Pre ffmpeg 5, the avformat_new_stream() function worked like this:
```
s = media file handle
c = If non-NULL, the AVCodecContext corresponding to the new stream will be initialized to use this codec. This is needed for e.g. codec-specific defaults to be set, so codec should be provided if it is known.
```

But ffmpeg v5 and greater now ignores the codec information.
```
s = media file handle
c = unused, does nothing
```

So various parameters on the stream related to the codec are not being set, and therefore:
```
        let mut encoder = codec::context::Context::from_parameters(ost.parameters())?
            .encoder()
            .video()?;
```
sets up an encoder (i.e. codec context) based on parameters (ost.parameters()) that won't have been correctly set.

Note that this example doesn't necessarily explain the fact that frame_rate is not set, but is indicative of the fact that there are likely (many) other breaking changes in the ffmpeg codebase that have not been propagated through this codebase.

Note that I've tried getting this transcoder code to work with ffmpeg versions <= 4 and they still break.  The only success I had was reverting both ffmpeg AND this repo to a commit from October 2021.

Unfortunately I'm not experienced enough with rust to be able to offer suggestions as to fixes right now.

**Comment by fuzing** [comment]
Further to my earlier comment, the following will work for setting the framerate, provided you want the output (encoder) rate to equal the input (decoder rate):
```
   encoder.set_frame_rate(Some(ist.avg_frame_rate()));
   encoder.set_time_base(ist.avg_frame_rate().invert());
```
The
```
   ist.rate()
```
Could also be used.  Here, I'm just making the frame_rate and time_base equivalent to those found on the input stream.

Alas, the code then breaks at:
```
   encoder
          .open_with(x264_opts)
          .expect("error opening libx264 encoder with supplied settings");
```
due to an
```
    avcodec_open2()
```
call with bad data (it complains that no codec is being passed, likely as a result of incorrect encoder (context) setup as outlined in my previous comment.

**Comment by fuzing** [comment]
After messing around with this crate I've now found quite a few breaking API changes......... there don't appear to be any decent safe bindings for ffmpeg for rust......... so have abandoned rust ffmpeg in favor of gstreamer, which has excellent rust support.

**Comment by Type1J** [comment]
I'm looking for a crate that I can create a DASH init.mp4 and many segment files from RGB frames. I believe this crate to be the one to do so, but it seems to be currently broken. Hopefully, someone will fix it soon.

**Comment by nununoisy** [comment]
I have a working encoder implementation here (MIT licensed): https://github.com/nununoisy/spc-presenter-rs/tree/v0.1.1/src/video_builder

I've verified it works for:
- H.264 (libx264, yuv420p) + AAC (aac, fltp) in MP4
- H.264 + AAC in MKV
- H.264 + AAC in MOV
- ProRes 4444 (prores_ks, yuv444p10le) + AAC in MOV

I did need to write some `unsafe` functions to interact with `ffmpeg-sys-next` directly in some cases. Hopefully, those functions can be used to extend the current API to allow for constructing a working encoder.

**Comment by iamdb** [comment]
I just started a project using this crate and am seeing this issue attempting to implement the transcode-x264 example.

Is there a workaround for this or a reason a PR hasn't been merged to address it?

**Comment by carlosdp** [comment]
For anyone else running into this, the library *does* have support for v6+ (and the v7 that just launched today, props to the guy who merged that on launch day 🥳 ), **but** as mentioned above, the API is a little different than v4, and the transcoding x264 example is assuming ffmpeg v4.

The fix is very simple to make it v6/v7 compatible:

```rust
// old
let output_context = ffmpeg::codec::context::Context::from_parameters(otx.parameters())?;
// new
let codec = ffmpeg::encoder::find(ffmpeg::codec::Id::H264)?;
let output_context = ffmpeg::codec::context::Context::new_with_codec(codec);
```

also, toward the end of `Transcoder::new()`, ignore the part where they re-initialize a new encoder from the output parameters for some reason, and instead use the one returned from the `open_with` command:

```rust
encoder = encoder.open_with(libx264_opts)?;
```

**Comment by Polochon-street** [comment]
> For anyone else running into this, the library _does_ have support for v6+ (and the v7 that just launched today, props to the guy who merged that on launch day 🥳 ), **but** as mentioned above, the API is a little different than v4, and the transcoding x264 example is assuming ffmpeg v4.
> 
> The fix is very simple to make it v6/v7 compatible:
> 
> ```rust
> // old
> let output_context = ffmpeg::codec::context::Context::from_parameters(otx.parameters())?;
> // new
> let codec = ffmpeg::encoder::find(ffmpeg::codec::Id::H264)?;
> let output_context = ffmpeg::codec::context::Context::new_with_codec(codec);
> ```
> 
> also, toward the end of `Transcoder::new()`, ignore the part where they re-initialize a new encoder from the output parameters for some reason, and instead use the one returned from the `open_with` command:
> 
> ```rust
> encoder = encoder.open_with(libx264_opts)?;
> ```

hi!

Would you make a PR with a conditional compilation depending on the ffmpeg version (like this for instance https://github.com/zmwangx/rust-ffmpeg/blob/master/src/codec/capabilities.rs#L9) that would make it compatible with ffmpeg6 onwards? I wouldn't mind merging it :)
