### ISSUE TITLE
Input picture width (960) is greater than stride (0)

### ISSUE THREAD

**Issue by michelvocks** [zmwangx/rust-ffmpeg#82]
Hey 👋 

Thanks for this great library. Love it so far.

I'm having kinda a bit of a hard time to record the screen in one pixel format (e.g. uyvy422) and then do the decoding of the output to a file in a different pixel format (e.g. yuv420p kinda required for videos that should be playable on the web) with AVFOUNDATION (MacOS). If I use different pixel formats then it works without any issues but I think `yuv420p` is the problem here. I'm not yet sure if this is really dependent on MacOS but I will give it a try on windows as well.

```
[libx264 @ 0x7fa268031200] Input picture width (960) is greater than stride (0)
```

I you google this issue you will eventually find this thread: https://stackoverflow.com/a/34478959. I tried to figure out the linestride and image planes (you can see the debug output in the error message below) in my test app. In the answer it is mentioned that for YUV which is 4:2:0 that the stride must be at least half the width on the second and third plane. Apparently, only the first plane is set here somehow. All other planes are 0. I tried to understand why this is happening but I've failed yet to figure that out.

## Example program

```rust
extern crate ffmpeg_next as ffmpeg;
extern crate ctrlc;
extern crate strum;
#[macro_use]
extern crate strum_macros;

use std::hash::Hasher;
use ffmpeg::{codec, decoder, encoder, format, frame, picture, Dictionary, Packet, Rational, Format, color};
use std::time::Instant;
use ffmpeg::media::Type;
use std::thread;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

const DEFAULT_X264_OPTS: &str = "preset=slower";

struct Transcoder {
    ost_index: usize,
    decoder: decoder::Video,
    encoder: encoder::video::Video,
    logging_enabled: bool,
    frame_count: i64,
    last_log_frame_count: i64,
    starting_time: Instant,
    last_log_time: Instant,
}

impl Transcoder {
    fn new(
        ist: &format::stream::Stream,
        octx: &mut format::context::Output,
        ost_index: usize,
        x264_opts: Dictionary,
        enable_logging: bool,
    ) -> Result<Self, ffmpeg::Error> {
        let global_header = octx.format().flags().contains(format::Flags::GLOBAL_HEADER);
        let decoder = ist.codec().decoder().video()?;
        let mut ost = octx.add_stream(encoder::find_by_name("libx264"))?;
        let mut encoder = ost.codec().encoder().video()?;
        encoder.set_height(decoder.height());
        encoder.set_width(decoder.width());
        encoder.set_aspect_ratio(decoder.aspect_ratio());
        encoder.set_format(format::Pixel::YUV420P);
        encoder.set_frame_rate(decoder.frame_rate());
        encoder.set_time_base(decoder.frame_rate().unwrap().invert());
        if global_header {
            encoder.set_flags(codec::Flags::GLOBAL_HEADER);
        }
        encoder
            .open_with(x264_opts)
            .expect("error opening libx264 encoder with supplied settings");
        encoder = ost.codec().encoder().video()?;
        ost.set_parameters(encoder);
        Ok(Self {
            ost_index,
            decoder,
            encoder: ost.codec().encoder().video()?,
            logging_enabled: enable_logging,
            frame_count: 0,
            last_log_frame_count: 0,
            starting_time: Instant::now(),
            last_log_time: Instant::now(),
        })
    }

    fn send_packet_to_decoder(&mut self, packet: &Packet) {
        self.decoder.send_packet(packet).unwrap();
    }

    fn send_eof_to_decoder(&mut self) {
        self.decoder.send_eof().unwrap();
    }

    fn receive_and_process_decoded_frames(
        &mut self,
        octx: &mut format::context::Output,
        ost_time_base: Rational,
    ) {
        let mut frame = frame::Video::empty();
        while self.decoder.receive_frame(&mut frame).is_ok() {
            self.frame_count += 1;
            let timestamp = frame.timestamp();
            self.log_progress(f64::from(
                Rational(timestamp.unwrap_or(0) as i32, 1) * self.decoder.time_base(),
            ));
            frame.set_pts(Some(self.frame_count));
            frame.set_kind(picture::Type::None);
            frame.set_color_range(color::Range::JPEG);
            println!("planes: {}", frame.planes());
            println!("height: {}; width: {}", frame.plane_height(0), frame.plane_width(0));
            println!("stride: {}", frame.stride(0));
            self.send_frame_to_encoder(&frame);
            self.receive_and_process_encoded_packets(octx, ost_time_base);
        }
    }

    fn send_frame_to_encoder(&mut self, frame: &frame::Video) {
        self.encoder.send_frame(frame).unwrap();
    }

    fn send_eof_to_encoder(&mut self) {
        self.encoder.send_eof().unwrap();
    }

    fn receive_and_process_encoded_packets(
        &mut self,
        octx: &mut format::context::Output,
        ost_time_base: Rational,
    ) {
        let mut encoded = Packet::empty();
        while self.encoder.receive_packet(&mut encoded).is_ok() {
            encoded.set_stream(self.ost_index);
            encoded.rescale_ts(self.decoder.time_base(), ost_time_base);
            encoded.write_interleaved(octx).unwrap();
        }
    }

    fn log_progress(&mut self, timestamp: f64) {
        if !self.logging_enabled
            || (self.frame_count - self.last_log_frame_count < 100
            && self.last_log_time.elapsed().as_secs_f64() < 1.0)
        {
            return;
        }
        eprintln!(
            "time elapsed: \t{:8.2}\tframe count: {:8}\ttimestamp: {:8.2}",
            self.starting_time.elapsed().as_secs_f64(),
            self.frame_count,
            timestamp
        );
        self.last_log_frame_count = self.frame_count;
        self.last_log_time = Instant::now();
    }
}

fn parse_opts<'a>(s: String) -> Option<Dictionary<'a>> {
    let mut dict = Dictionary::new();
    for keyval in s.split_terminator(',') {
        let tokens: Vec<&str> = keyval.split('=').collect();
        match tokens[..] {
            [key, val] => dict.set(key, val),
            _ => return None,
        }
    }
    Some(dict)
}

#[derive(AsRefStr)]
enum VideoDriver {
    AVFOUNDATION,
    GDIGRAB,
}

impl VideoDriver {
    fn to_lowercase(&self) -> String {
        str::to_lowercase(self.as_ref())
    }
}

fn main() {
    ffmpeg::init().unwrap();

    let mut input_options = ffmpeg::util::dictionary::Owned::new();
    let mut used_video_driver: VideoDriver = VideoDriver::GDIGRAB;
    let input_device: Format = match ffmpeg::device::input::video().into_iter().find(|device| device.name() == VideoDriver::GDIGRAB.to_lowercase()) {
        None => {
            // Maybe we're on MacOS
            match ffmpeg::device::input::video().into_iter().find(|device| device.name() == VideoDriver::AVFOUNDATION.to_lowercase()) {
                None => {
                    panic!("no compatible video capture driver found");
                }
                Some(device) => {
                    input_options.set("pixel_format", "yuv420p");
                    used_video_driver = VideoDriver::AVFOUNDATION;
                    device
                }
            }
        }
        Some(device) => {
            device
        }
    };
    input_options.set("framerate", "5");
    input_options.set("probesize", "100M");
    input_options.set("video_size", "1920x1080");

    let video_path = match used_video_driver {
        VideoDriver::AVFOUNDATION => std::path::Path::new("2:none"),
        VideoDriver::GDIGRAB => std::path::Path::new("desktop"),
    };
    let ctx = ffmpeg::format::open_with(&video_path, &input_device, input_options).unwrap();

    let mut input = ctx.input();
    let input_stream = input.streams().best(Type::Video).ok_or(ffmpeg::Error::StreamNotFound).unwrap();
    let video_stream_index = input_stream.index();

    const OUTPUT_FILE_NAME: &str = "test.mp4";
    let output_path = std::path::Path::new(OUTPUT_FILE_NAME);
    let mut octx = ffmpeg::format::output(&output_path).unwrap();

    let x264_opts = parse_opts(DEFAULT_X264_OPTS.to_string()).unwrap();

    let mut transcoder = Transcoder::new(
        &input_stream,
        &mut octx,
        video_stream_index as _,
        x264_opts.to_owned(),
        true,
    ).unwrap();

    octx.set_metadata(input_stream.metadata().to_owned());
    format::context::output::dump(&octx, 0, Some(OUTPUT_FILE_NAME));
    octx.write_header().unwrap();

    let exit_app = Arc::new(AtomicBool::new(false));

    let stream_time_base = octx.stream(video_stream_index as _).unwrap().time_base();
    let exit_app_clone = exit_app.clone();
    let handle = thread::spawn(move || {
        for (stream, mut packet) in input.packets() {
            if stream.index() == video_stream_index {
                packet.rescale_ts(stream.time_base(), transcoder.decoder.time_base());
                transcoder.send_packet_to_decoder(&packet);
                transcoder.receive_and_process_decoded_frames(&mut octx, stream_time_base);
            }

            // Exit app if required
            if exit_app_clone.load(Ordering::Relaxed) {
                println!("exit in recording thread called!");
                transcoder.send_eof_to_decoder();
                transcoder.receive_and_process_decoded_frames(&mut octx, stream_time_base);
                transcoder.send_eof_to_encoder();
                transcoder.receive_and_process_encoded_packets(&mut octx, stream_time_base);
                octx.write_trailer().unwrap();
                break;
            }
        }
    });

    ctrlc::set_handler(move || {
        println!("received Ctrl+C! Exiting...");
        exit_app.store(true, Ordering::Relaxed)
    }).expect("failed to set ctrl+c handler");

    handle.join().unwrap();
}
```

Cargo.toml
```
[package]
name = "ffmpeg-next-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-next = "4.4.0"
ctrlc = "3.2.0"
strum = "0.21"
strum_macros = "0.21"
```

## Error 

```
[libx264 @ 0x7fa268031200] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7fa268031200] profile High, level 5.0, 4:2:0, 8-bit
[libx264 @ 0x7fa268031200] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=8 deblock=1:0:0 analyse=0x3:0x133 me=umh subme=9 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=18 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=2 b_bias=0 direct=3 weightb=1 open_gop=1 weightp=2 keyint=250 keyint_min=5 scenecut=40 intra_refresh=0 rc_lookahead=60 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'test.mp4':
  Stream #0:0: Video: h264 (libx264), yuv420p, 1920x1080, q=-1--1, 5 tbc
planes: 1
height: 1080; width: 1920
stride: 3840
[libx264 @ 0x7fa268031200] Input picture width (960) is greater than stride (0)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ffmpeg::Error(542398533: Generic error in an external library)', src/main.rs:98:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/main.rs:245:19
```

**Comment by michelvocks** [comment]
I figured out that this is in fact not a bug. It is required to use the `scaling` framework to transform the image pixel format.

```rust
use ffmpeg::software::scaling::{context::Context, flag::Flags};

let frame_scaler = Context::get(
            decoder.format(),
            decoder.width(),
            decoder.height(),
            format::Pixel::YUV420P,
            decoder.width(),
            decoder.height(),
            Flags::BILINEAR,
        )?;

let mut raw_frame = frame::Video::empty();
        while self.decoder.receive_frame(&mut raw_frame).is_ok() {
            let mut scaled_frame = frame::Video::empty();
            if let Err(err) = frame_scaler.run(&raw_frame, &mut scaled_frame) {
                error!("failed to scale input frame: {}", err);
                continue;
            }
            self.frame_count += 1;
            let timestamp = raw_frame.timestamp();
            self.log_progress(f64::from(
                Rational(timestamp.unwrap_or(0) as i32, 1) * self.decoder.time_base(),
            ));
            scaled_frame.set_pts(Some(self.frame_count));
            self.send_frame_to_encoder(&scaled_frame);
            self.receive_and_process_encoded_packets(octx, ost_time_base);
        }
```
(does not work but should give a hint how it can/should be used)
